name: Tom Wentworth
favicon: null
layout_spectrum: 0.25207
typography_spectrum: 0.61997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9c69b'
    - '#b8aa81'
    - '#313534'
    - '#7d8e70'
    - '#505c52'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
