name: Tom Wentworth
favicon: null
layout_spectrum: 0.24503
typography_spectrum: 0.4001
title: perpetual motion
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffc6'
    - '#835940'
    - '#060004'
    - '#fef102'
    - '#750f1c'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
