name: Tom Wentworth
favicon: null
layout_spectrum: 0.9627140713855624
typography_spectrum: 0.6463489399757236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.902087606722489
  lightness: 0.7586523271165788
  saturation: 0.7389309832360595
  rhythmicContrast: 0.9745324060786515
purpose: []
